preprocess:
  binary_threshold: 140
  enemy_color: 0        # 0: UNKNOWN, 1: RED, 2: BLUE

light:
  min_light_ratio: 4.0
  max_light_ratio: 20.0
  max_light_angle: 30.0

armor:
  min_small_center_dist: 2.0
  max_small_center_dist: 4.0
  min_large_center_dist: 4.0
  max_large_center_dist: 10.0
  max_angle_diff: 15.0
