# Detector参数
binary_threshold: 135
# enemy_color: 0        # 0: RED, 1: BLUE
# kernel_size: 
#   width: 7
#   height: 7
detect_color: 1

light:
  min_light_ratio: 5.0
  max_light_ratio: 20.0
  max_light_angle: 45.0

armor:
  min_small_center_dist: 2.0 # 2.0
  max_small_center_dist: 3.2 # 4.0

  min_large_center_dist: 3.6 # 4.0
  max_large_center_dist: 6.5 # 10.0

  max_angle_diff: 15.0

# 相机参数
camera_matrix: [ 612.60753305346861, 0., 321.05152577984717, 0., 
  610.59384985835243, 211.76660513686494, 0., 0., 1. ]

dist_coeffs: [ -0.0037713809997581668, 0.20059741673851425,
  -0.0012236672927694533, -0.0030975157829330894, -0.58124045250100609 ]