camera:
  active: usb       

  usb:
    device_id: 0
    width: 640
    height: 480
    fps: 60

  # hikrobot:
  #   exposure_ms: 3
  #   gain: 10.0
  #   vid_pid: "2bdf:0001"

  # mindvision:
  #   exposure_ms: 2
  #   gamma: 0.5
  #   vid_pid: "f622:d13a"
